# Generated by Django 6.0 on 2025-12-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetperiod',
            name='period_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('custom', 'Custom Dates'), ('pay_period', 'Pay Period')], default='monthly', max_length=20),
        ),
    ]
