# Generated by Django 6.0 on 2025-12-11 20:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_budgetperiod_period_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetperiod',
            name='start_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='payday',
            name='payday_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='budgetperiod',
            index=models.Index(fields=['user', 'start_date'], name='budget_budg_user_id_41e7e4_idx'),
        ),
        migrations.AddIndex(
            model_name='payday',
            index=models.Index(fields=['budget_period', 'payday_date'], name='budget_payd_budget__26352e_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['budget_period', 'date'], name='budget_tran_budget__8132d4_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'date'], name='budget_tran_user_id_fcff6a_idx'),
        ),
    ]
